#!/usr/bin/env bash
# Security checks for this project. Auto-detects what applies:
#   pip-audit  - known vulnerabilities in Python requirements
#   bandit     - Python static analysis (medium+ severity)
#   npm audit  - known vulnerabilities in Node lockfiles (high+)
#   gitleaks   - secret scan (git history, or working tree if no repo)
# Also refreshes this project's dependency inventory in the sibling
# dl-tech-digest repo so the daily digest routine can match CVEs
# against our real dependencies. `--inventory-only` skips the scans.
# Exits non-zero if any check reports issues. Identical copy in every
# project; auto-detection keeps it stack-agnostic.
set -u
cd "$(dirname "$0")"

FAIL=0
run() {
  local label=$1; shift
  echo "== $label"
  if "$@"; then echo "-- OK"; else FAIL=1; echo "-- ISSUES FOUND"; fi
  echo
}
have() { command -v "$1" >/dev/null 2>&1; }
skip() { echo "== $1"; echo "-- SKIPPED ($2 not installed)"; echo; }

PRUNE=( -not -path '*/node_modules/*' -not -path '*/venv/*' \
        -not -path '*/.venv/*' -not -path '*/__pycache__/*' \
        -not -path '*/.claude/*' )

# Dependency inventory for the digest routine (see dl-tech-digest
# docs/routine-prompt.md). No timestamp: output only changes when
# dependencies do, so publishing can be change-driven. A .digest-exclude
# file in the project root opts it out of digest coverage.
if [ -d ../dl-tech-digest ] && [ ! -f .digest-exclude ]; then
  mkdir -p ../dl-tech-digest/inventory
  {
    echo "# $(basename "$(pwd)") — dependency inventory"
    echo "Generated by security-check.sh; do not edit by hand."
    while IFS= read -r req; do
      echo; echo "## Python: $req"
      grep -vE '^[[:space:]]*(#|$|-r|--)' "$req"
    done < <(find . -name 'requirements*.txt' "${PRUNE[@]}" | sort)
    if have python3; then
      while IFS= read -r lock; do
        echo; echo "## Node: $lock"
        python3 - "$lock" <<'PY'
import json, sys
pkgs = json.load(open(sys.argv[1])).get('packages', {})
root = pkgs.get('', {})
names = set(root.get('dependencies', {})) | set(root.get('devDependencies', {}))
for n in sorted(names):
    print(n, pkgs.get('node_modules/' + n, {}).get('version', '?'))
PY
      done < <(find . -name 'package-lock.json' "${PRUNE[@]}" | sort)
    fi
  } > "../dl-tech-digest/inventory/$(basename "$(pwd)").md"
fi
[ "${1:-}" = "--inventory-only" ] && exit 0

# Python dependency audit
while IFS= read -r req; do
  if have pip-audit; then
    run "pip-audit: $req" pip-audit -r "$req"
  else
    skip "pip-audit: $req" pip-audit
  fi
done < <(find . -name 'requirements*.txt' "${PRUNE[@]}")

# Python static analysis
if find . -name '*.py' "${PRUNE[@]}" | grep -q .; then
  if have bandit; then
    run "bandit (medium+ severity)" bandit -q -r . -ll \
      -x '*/venv/*,*/.venv/*,*/node_modules/*,*/__pycache__/*,*/migrations/*'
  else
    skip "bandit" bandit
  fi
fi

# Node dependency audit (npm audit needs a lockfile)
while IFS= read -r pkg; do
  dir=$(dirname "$pkg")
  if [ ! -f "$dir/package-lock.json" ]; then
    echo "== npm audit: $dir"
    echo "-- SKIPPED (no package-lock.json; run 'npm i --package-lock-only' there)"
    echo
  elif have npm; then
    run "npm audit: $dir" npm audit --prefix "$dir" --audit-level=high
  else
    skip "npm audit: $dir" npm
  fi
done < <(find . -name 'package.json' "${PRUNE[@]}")

# Secret scan
if have gitleaks; then
  if [ -d .git ]; then
    run "gitleaks (git history)" gitleaks git --no-banner --redact -v --exit-code 1 .
  else
    run "gitleaks (working tree)" gitleaks dir --no-banner --redact -v --exit-code 1 .
  fi
else
  skip "gitleaks" gitleaks
fi

exit $FAIL
