#!/usr/bin/env bash
# Security checks for this project. Auto-detects what applies:
#   pip-audit  - known vulnerabilities in Python requirements
#   bandit     - Python static analysis (medium+ severity)
#   npm audit  - known vulnerabilities in Node lockfiles (high+)
#   gitleaks   - secret scan (git history, or working tree if no repo)
# Also refreshes this project's dependency inventory in the sibling
# dl-tech-digest repo so the daily digest routine can match CVEs
# against our real dependencies, transitive ones included.
# `--inventory-only` skips the scans.
# Exits non-zero if any check reports issues. Identical copy in every
# project; auto-detection keeps it stack-agnostic.
set -u
cd "$(dirname "$0")"

FAIL=0
run() {
  local label=$1; shift
  echo "== $label"
  if "$@"; then echo "-- OK"; else FAIL=1; echo "-- ISSUES FOUND"; fi
  echo
}
have() { command -v "$1" >/dev/null 2>&1; }
skip() { echo "== $1"; echo "-- SKIPPED ($2 not installed)"; echo; }

PRUNE=( -not -path '*/node_modules/*' -not -path '*/venv/*' \
        -not -path '*/.venv/*' -not -path '*/__pycache__/*' \
        -not -path '*/.claude/*' )

# Dependency inventory for the digest routine (see dl-tech-digest
# docs/routine-prompt.md). Direct deps are listed as declared; transitive
# deps at the exact version a fresh install resolves to today (Node: the
# lockfile; Python: a pip dry-run against the index), each tagged
# "# via" with the packages that require it so a CVE hit traces back to
# the direct dep to bump. Resolved versions drift as upstream publishes —
# publish-inventory.yml refreshes weekly. No timestamp, so an unchanged
# tree publishes nothing. A .digest-exclude file in the project root opts
# the project out of digest coverage.
if [ -d ../dl-tech-digest ] && [ ! -f .digest-exclude ]; then
  mkdir -p ../dl-tech-digest/inventory
  {
    echo "# $(basename "$(pwd)") — dependency inventory"
    echo "Generated by security-check.sh; do not edit by hand."
    while IFS= read -r req; do
      echo; echo "## Python: $req"
      grep -vE '^[[:space:]]*(#|$|-r|--)' "$req"
      echo; echo "## Python transitive: $req"
      if have python3; then
        # --dry-run never touches site-packages, so this is safe outside a
        # venv; --ignore-installed makes the report cover the whole tree.
        python3 - "$req" <(python3 -m pip install --dry-run --ignore-installed \
          -q --report - -r "$req" 2>/dev/null) <<'PY'
import json, os, re, sys
norm = lambda n: re.sub(r'[-_.]+', '-', n).lower()
def parse(req):  # 'sqlalchemy[asyncio]>=2' -> ('sqlalchemy', {'asyncio'})
    m = re.match(r'\s*([A-Za-z0-9][A-Za-z0-9._-]*)(?:\[([^\]]*)\])?', req)
    return norm(m[1]), {norm(e.strip()) for e in (m[2] or '').split(',') if e.strip()}
declared = {}  # name -> extras asked for; -r includes are declared too
def read(path):
    for line in open(path):
        line = line.strip()
        inc = re.match(r'(?:-r|--requirement)\s+(\S+)', line)
        if inc:
            read(os.path.join(os.path.dirname(path), inc[1]))
        elif line and line[0] not in '#-':
            name, extras = parse(line)
            declared.setdefault(name, set()).update(extras)
read(sys.argv[1])
try:
    tree = json.load(open(sys.argv[2]))['install']
except ValueError:
    print('(pip resolution failed)'); sys.exit()
versions = {norm(i['metadata']['name']): i['metadata']['version'] for i in tree}
# Who requires whom, from each package's Requires-Dist. A requirement
# gated on an extra counts only once someone asks for that extra
# (fonttools[woff] -> brotli), so extras propagate until nothing changes.
edges = []
for i in tree:
    parent = norm(i['metadata']['name'])
    for req in i['metadata'].get('requires_dist') or []:
        child, extras = parse(req)
        gate = re.search(r'''extra\s*==\s*['"]([^'"]+)''', req)
        if child in versions:
            edges.append((parent, child, extras, gate and norm(gate[1])))
via = {n: set() for n in versions}
extras = {n: set(declared.get(n, ())) for n in versions}
changed = True
while changed:
    changed = False
    for parent, child, want, gate in edges:
        if (gate is None or gate in extras[parent]) and (parent not in via[child] or not want <= extras[child]):
            via[child].add(parent); extras[child] |= want; changed = True
for name in sorted(versions):
    if name not in declared:
        parents = ', '.join(sorted(via[name]))
        print(f'{name}=={versions[name]}' + (f'  # via {parents}' if parents else ''))
PY
      else
        echo "(python3 not installed)"
      fi
    done < <(find . -name 'requirements*.txt' "${PRUNE[@]}" | sort)
    if have python3; then
      while IFS= read -r lock; do
        echo; echo "## Node: $lock"
        python3 - "$lock" <<'PY'
import json, sys
pkgs = json.load(open(sys.argv[1])).get('packages', {})
root = pkgs.get('', {})
direct = set(root.get('dependencies', {})) | set(root.get('devDependencies', {}))
# Nested copies (a/node_modules/b) collapse onto the package name; a name
# installed at several versions lists them all. via = who requires whom,
# peers included since npm installs them automatically.
versions, via = {}, {}
for path, meta in pkgs.items():
    if path:
        name = path.rsplit('node_modules/', 1)[1]
        versions.setdefault(name, set()).add(meta.get('version', '?'))
        for kind in ('dependencies', 'optionalDependencies', 'peerDependencies'):
            for child in meta.get(kind) or {}:
                via.setdefault(child, set()).add(name)
def show(names, chains=False):
    for n in sorted(names):
        line = f"{n} {', '.join(sorted(versions.get(n, {'?'})))}"
        parents = ', '.join(sorted(via.get(n, ())))
        print(line + (f'  # via {parents}' if chains and parents else ''))
show(direct)
print(); print('## Node transitive:', sys.argv[1])
show(versions.keys() - direct, chains=True)
PY
      done < <(find . -name 'package-lock.json' "${PRUNE[@]}" | sort)
    fi
  } > "../dl-tech-digest/inventory/$(basename "$(pwd)").md"
fi
[ "${1:-}" = "--inventory-only" ] && exit 0

# Python dependency audit
while IFS= read -r req; do
  if have pip-audit; then
    run "pip-audit: $req" pip-audit -r "$req"
  else
    skip "pip-audit: $req" pip-audit
  fi
done < <(find . -name 'requirements*.txt' "${PRUNE[@]}")

# Python static analysis
if find . -name '*.py' "${PRUNE[@]}" | grep -q .; then
  if have bandit; then
    run "bandit (medium+ severity)" bandit -q -r . -ll \
      -x '*/venv/*,*/.venv/*,*/node_modules/*,*/__pycache__/*,*/migrations/*'
  else
    skip "bandit" bandit
  fi
fi

# Node dependency audit (npm audit needs a lockfile)
while IFS= read -r pkg; do
  dir=$(dirname "$pkg")
  if [ ! -f "$dir/package-lock.json" ]; then
    echo "== npm audit: $dir"
    echo "-- SKIPPED (no package-lock.json; run 'npm i --package-lock-only' there)"
    echo
  elif have npm; then
    run "npm audit: $dir" npm audit --prefix "$dir" --audit-level=high
  else
    skip "npm audit: $dir" npm
  fi
done < <(find . -name 'package.json' "${PRUNE[@]}")

# Secret scan
if have gitleaks; then
  if [ -d .git ]; then
    run "gitleaks (git history)" gitleaks git --no-banner --redact -v --exit-code 1 .
  else
    run "gitleaks (working tree)" gitleaks dir --no-banner --redact -v --exit-code 1 .
  fi
else
  skip "gitleaks" gitleaks
fi

exit $FAIL
